<a href="https://colab.research.google.com/github/mehedihasan-cse/Data-Science-Practice--Advance-Topic/blob/main/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [ ]:
# A vector is a one-dimensional array of numbers, while a matrix is a two-dimensional array of numbers.

**2. How to import `NumPy` library?**

In [ ]:
import numpy as np


**3. Convert the given Python list into NumPy array and check its data type**

In [ ]:
list_1 = [1,2,3,4,5]

In [ ]:
import numpy as np
list_1 = [1,2,3,4,5]
my_array = np.array(list_1)
my_array, type(my_array)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [ ]:
import numpy as np
np.arange(6)

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [ ]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [ ]:
import numpy as np
array_arange = np.zeros(12)
array_arange.reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [ ]:
import numpy as np
array_arange = np.ones(5)
array_arange

array([1., 1., 1., 1., 1.])

[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [ ]:
import numpy as np
tens_array = np.full(5, 10.0)
tens_array

array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [ ]:
import numpy as np
array_arange = np.arange(52,100, 2)
array_arange

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [ ]:
import numpy as np
np_linspace = np.linspace(0, 1, 10, retstep=True)
np_linspace

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [ ]:
import numpy as np
vector_array= np.arange(25)
vector_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
vector_array = vector_array.reshape(5,5)
vector_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
vector_array.shape= (5,5)
vector_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [ ]:
x = np.arange(.1,2.6, 0.1 , dtype=float)
x
x = x.reshape(5,5)
x


array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [ ]:
x= np.linspace(0,24, 25, dtype=int)
x
x= x.reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [ ]:
# The main difference between linspace() and arange() in NumPy lies in how they handle the specification of the range of values.

# arange() takes 3rd argument as step size.
# import numpy as np
# arr = np.arange(0, 10, 2)
# print(arr)


# linspace() take 3rd argument as no of point we want.
# import numpy as np
# arr = np.linspace(0, 10, 5)
# print(arr)


**15. How to generate a single random integer number using NumPy built-in function?**

In [ ]:
np.random.randint(1,100,1)

array([58])

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [ ]:
rand_matrix = np.random.rand(7,5)
print(rand_matrix)

[[0.17641951 0.42833308 0.77517907 0.1616678  0.36631475]
 [0.99038731 0.88045404 0.49875071 0.41562352 0.85996463]
 [0.84578164 0.92382894 0.90798958 0.22703892 0.5768509 ]
 [0.71539173 0.7191561  0.91699948 0.57132395 0.48196083]
 [0.3325167  0.98300243 0.17742411 0.47176646 0.11331294]
 [0.90648987 0.85982983 0.14314961 0.74510918 0.0180969 ]
 [0.95254933 0.40758747 0.03479106 0.5261119  0.66528181]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
x= 5* np.identity(5)
x

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck